// <auto-generated />
using System;
using BTCPayServer.Plugins.Flint.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Flint.Migrations
{
    [DbContext(typeof(SparkPluginDbContext))]
    [Migration("20260804161138_OutgoingPaymentStoreScopedKey")]
    partial class OutgoingPaymentStoreScopedKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Flint")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Flint.Data.InvoiceRecord", b =>
                {
                    b.Property<string>("PaymentHash")
                        .HasColumnType("text");

                    b.Property<long?>("AmountMsat")
                        .HasColumnType("bigint");

                    b.Property<long?>("AmountReceivedMsat")
                        .HasColumnType("bigint");

                    b.Property<string>("Bolt11")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Preimage")
                        .HasColumnType("text");

                    b.Property<string>("SdkPaymentId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentHash");

                    b.HasIndex("StoreId", "CreatedAt");

                    b.HasIndex("StoreId", "Status");

                    b.ToTable("InvoiceRecords", "BTCPayServer.Plugins.Flint");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Flint.Data.OutgoingPaymentRecord", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentHash")
                        .HasColumnType("text");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Bolt11")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreId", "PaymentHash");

                    b.HasIndex("StoreId", "FirstAttemptAt");

                    b.ToTable("OutgoingPayments", "BTCPayServer.Plugins.Flint");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Flint.Data.SweepRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<long>("AmountSats")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<long?>("FeeSats")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TxId")
                        .HasColumnType("text");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("StoreId", "CreatedAt");

                    b.ToTable("SweepRecords", "BTCPayServer.Plugins.Flint");
                });
#pragma warning restore 612, 618
        }
    }
}
