using System;
using System.IO;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Contracts;
using Newtonsoft.Json.Linq;

namespace BTCPayServer.Plugins.Flint.Services;

/// <summary>
/// Contributes the Spark endpoints to BTCPay's OpenAPI document, so they show up in the server's own API docs and
/// in anything generated from them.
/// </summary>
/// <remarks>
/// <para>
/// BTCPay merges every registered <see cref="ISwaggerProvider"/>'s document into one at
/// <c>/swagger/v1/swagger.json</c>. Core's own provider reads the JSON fragments under its web root; a plugin has no
/// web root, so the fragment is an embedded resource in this assembly instead — the pattern Boltz's plugin uses for
/// the same purpose.
/// </para>
/// <para>
/// <b>Deliberately depends on nothing.</b> This is registered as a singleton the host may enumerate, and
/// resolving <c>IEnumerable&lt;T&gt;</c> materialises every registration — so this type is constructed while
/// BTCPay is still building itself. An object graph that reaches back into that construction deadlocks startup
/// silently, because the container cannot see a cycle that runs through a factory delegate. Reading one embedded
/// string needs no services, so it takes none.
/// </para>
/// <para>
/// The fragment is <b>hand-written</b> rather than generated by reflection over the controller. That is a
/// maintenance cost accepted on purpose: the parts of this API that most need documenting are the ones no generator
/// could infer — that a mnemonic is returned exactly once, that a balance is indicative, that a <c>200</c> from the
/// sweep endpoint does not mean money moved, and which API-key permission each route needs.
/// </para>
/// </remarks>
public sealed class SparkSwaggerProvider : ISwaggerProvider
{
    /// <summary>
    /// Manifest name of the embedded fragment. <c>Resources\**</c> is embedded by the csproj, and the resource name
    /// is the root namespace plus the path with separators replaced by dots.
    /// </summary>
    private const string ResourceName = "BTCPayServer.Plugins.Flint.Resources.swagger.json";

    private readonly Lazy<Task<JObject>> _document = new(LoadAsync);

    public Task<JObject> Fetch() => _document.Value;

    private static async Task<JObject> LoadAsync()
    {
        await using var stream = typeof(SparkSwaggerProvider).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"The Spark plugin's OpenAPI fragment ({ResourceName}) is missing from the assembly. It is an "
                + "EmbeddedResource under Resources/ — check the csproj if this build dropped it.");

        using var reader = new StreamReader(stream);
        return JObject.Parse(await reader.ReadToEndAsync().ConfigureAwait(false));
    }
}
